[project]
name = "repl-nix-londontransitalert"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.5",
    "apscheduler>=3.10.4",
    "asyncio",
    "python-telegram-bot>=21.7",
    "pytz>=2024.2",
]
